### ISSUE TITLE
How many FPS did you get with a Jetson Nano?

### ISSUE THREAD

**Issue by phamdat09** [stereolabs/zed-3d-social-distancing#1]
Hello, 
As I read your blog, your code runs real-time with a jetson nano. 
However, when I use your code with a Jetson Nano, I only get 2 or 3 FPS. 
I use the SDK 3.1.2.

Did you have some special setup with jetson nano? 
Thanks!!

**Comment by obraun-sl** [comment]
Hi,
Internally we are using Jetpack 4.4 and ZED SDK 3.2 which bring a lot of performance improvement. This combination is not yet available currently (in QA), but will be release hopefully end of this week or next week. 
With this combination and by removing GUI stuff, we have around 8-9FPS which makes it usable on nano.

**Comment by phamdat09** [comment]
Thank for your reply !
will see with a new version of SDK!!
